name: Lint
# Lint runs golangci-lint over the entire Tendermint repository
# This workflow is run on every pull request and push to master
# The `golangci` job will pass without running if no *.{go, mod, sum} files have been modified.
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - name: Set GOPATH
        run: |
          echo "::set-env name=GOPATH::$(go env GOPATH)"
      - name: Set CGO_LDFLAGS
        run: |
          echo "::set-env name=CGO_LDFLAGS::"-L${GOPATH}/src/github.com/quantumexplorer/bls-signatures/build""
      - name: Set CGO_CXXFLAGS
        run: |
          echo "::set-env name=CGO_CXXFLAGS::"-I${GOPATH}/src/github.com/quantumexplorer/bls-signatures/src -I${GOPATH}/src/github.com/quantumexplorer/bls-signatures/contrib/relic/include -I${GOPATH}/src/github.com/quantumexplorer/bls-signatures/build/contrib/relic/include""
      - name: test & coverage report creation
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v1
        with:
          SUFFIX_FILTER: |
            .go
            .mod
            .sum
      - uses: golangci/golangci-lint-action@master
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.28
          args: --timeout 10m
          github-token: ${{ secrets.github_token }}
        if: "env.GIT_DIFF != ''"
